### ISSUE TITLE
Two questions on your paper

### ISSUE THREAD

**Issue by hihunjin** [Muzammal-Naseer/Intriguing-Properties-of-Vision-Transformers#2]
Hi. This is heonjin.

Firstly, big thanks to you and your paper. well-read and precise paper!
I have two questions on your paper.

1) Please take a look at Figure 9.
![image](https://user-images.githubusercontent.com/32363064/121481529-2f2d1e80-ca07-11eb-8489-e74a31dde30b.png)
On the 'no positional encoding' experiment, there is a peak on 196 shuffle size of "DeiT-T-no-pos". Why is there a peak? and I wonder why there is a decreasing from 0 shuffle size to 64 of "DeiT-T-no-pos".

2) On the Figure 14,
![image](https://user-images.githubusercontent.com/32363064/121481366-060c8e00-ca07-11eb-8048-2752f4304e29.png)
On the Aircraft(few shot), Flower(few shot) dataset, CNN performs better than DeiT. Could you explain this why?

Thanks in advance.

**Comment by kahnchana** [comment]
1) ViT models have an intrinsic grid operation (the input image is split into a 14x14 grid and each patch is converted to a patch token). In this experiment, we split the input image into a set of patches using a grid of a selected size and shuffle those patches to obtain a corrupted image. 
When we use a DeiT model with no positional encoding, if the input image is corrupted using a grid size that is a factor of 14x14 (that used in the DeiT model's intrinsic grid operation), this would correspond to simply shuffling the intermediate patch tokens in some specific manner. A ViT model would be aware of such a corruption only through the positional embeddings as all the transformer blocks are set-to-set operations. Within each individual patch, no corruptions occur. 
In the case of Figure 9, along the x-axis positions 0 (no shuffle), 4 (2x2 grid), and 196 (14x14 grid) are factors 14x14 (the DeiT model's intrinsic grid operation). Therefore, for a DeiT model with no positional encoding, this should theoretically lead to no change in model output. This behaviour is also observed empirically in Figure 9, when the model exhibits similar performance for these values (y-axis at x-axis positions 0, 4, 196). 
In the case of the other shuffle operations (which do not align with the 14x14 grid), performance degradation occurs since the inputs to each patch token changes (within one patch there would be corruptions). Hence, we notice drops for the other grid sizes.  

2) While we cannot be certain about the reasoning for such behaviour, we can note that Aircraft and Flower are small fine-grained datasets and may benefit heavily from features different to those useful for the other datasets.

**Comment by hihunjin** [comment]
Thanks all crystal clear.
